const cars = [ ];
cars.push("Lexus");
cars.push("Peuguot");
cars.push("volvo");
cars.push("Honda");

cars.splice(3, 0, "Fiat")
console.log(cars.join("\n"));

// sort() method
const fruits = ["Banana", "Orange", "Mango", "Pineapple"];
console.log(fruits.sort())

const evenNumber = ["8", "4", "9", "5", "2"];
console.log(evenNumber.sort());


// reverse method
console.log(fruits.reverse())
console.log(evenNumber.reverse());


document.write("<h1> This is Javascript </h1>");
document.write("<h2>" + fruits.join (", ") + "</h2>");

























// String

let greetings = "Good Morning world";
let message = "I love programming in Javascript";
let day = "Today is a beautiful day";
let house = "The house is up stairs";
let food = "Pounded Yam is my favorite food";
let watch = "Wrist watch is Mont Blanc";
let color = "My favorite color is Gold";
let knowledge = "Learning new things is exciting";
let music = "I enjoy listening to music while working.";
let life = "Life is full of surprises"



// Number

let temperature = 25;
let siblings = 3;
let kilometer = 100;
let storeOpen = 9;
let mathScore = 85;
let earthCircumference = 40750;
let phoneStorage = 512;
let population = 100000;
let rightAngel = 90;
let printColor = 4;


// Boolean

let isRaining = true;
let isSunny = false;
let isWing = false;
let isMovieStart = true;
let isLanguage = true;
let isLoggedIn = true;
let isSchool = false;
let isWatch = false;
let isBaby = false;






