const cars = [ ];
cars.push("Lexus");
cars.push("Peuguot");
cars.push("volvo");
cars.push("Honda");

cars.splice(3, 0, "Fiat")
console.log(cars.join("\n"));

// sort() method
const fruits = ["Banana", "Orange", "Mango", "Pineapple"];
console.log(fruits.sort())

const evenNumber = ["8", "4", "9", "5", "2"];
console.log(evenNumber.sort());


// reverse method
console.log(fruits.reverse())
console.log(evenNumber.reverse());


document.write("<h1> This is Javascript </h1>");
document.write("<h2>" + fruits.join (", ") + "</h2>");

























// String

let greetings = "Good Morning world";
let message = "I love programming in Javascript";
let day = "Today is a beautiful day";




